### PR TITLE
Added serverless-plugin-simulate

### PR DESCRIPTION
**Pull request by gertjvr**

### CODE REVIEW

**Comment by pmuens** [comment]
@gertjvr thanks for the PR (and for the plugin) 🎉 

It seems like someone already added it to the list: https://github.com/serverless/plugins/blob/5a7523a77d71277d5125cae950fbedb8c7032cfc/plugins.json#L73-L76

**Comment by gertjvr** [comment]
Didn't see it thx

**Comment by gertjvr** [comment]
@pmuens How long does it take to become visible in the readme?

**Comment by pmuens** [comment]
Oh. Yes. You need to run `npm run docs` before submitting the PR.

Would you like to submit a new PR with the `README` update by running this command? This way the `README` is updated and you appear as a contributor 👍 

Otherwise I can do it as well..

**Comment by pmuens** [comment]
Thanks! 👍

**Pull request closed without merging**
