### PR TITLE
Add yet another DynamoDB autoscaling plugin

### PR DESCRIPTION
**Pull request by hassankhan**

### CODE REVIEW

**Comment by eahefnawy** [comment]
Hey @hassankhan, thanks for the PR. Could you regenerate the README?

> After adding your plugin to the plugins.json file, run npm run docs to regenerate the plugin list table in the readme.md file.

**Comment by hassankhan** [comment]
Whoops, my bad, will do ASAP

PS: Might it be an idea to set up Travis on this repo and have it automatically run `npm run docs` on pushes/PRs?

**Comment by hassankhan** [comment]
Should be all good now 👍

**Comment by eahefnawy** [comment]
Thanks @hassankhan ... could you resolve conflicts so I could merge right away? 😊

**Comment by hassankhan** [comment]
All done @eahefnawy 👍

**Pull request merged**
