### PR TITLE
Add serverless-do-nothing

### PR DESCRIPTION
**Pull request by smileatom**
A serverless plugin template project that does nothing.

### CODE REVIEW

**Comment by patrickr** [comment]
Why?

**Comment by waveatom** [comment]
Its a template project for sls plugin writers to possibly start from.

**Comment by patrickr** [comment]
> Its a template project for sls plugin writers to possibly start from.

Sorry that was very rude of me. I feel really silly now 😅, Somehow I missed the word "template" and was thinking "why would you add a plugin that does nothing". Need more ☕️ before I read my github notifications

**Comment by waveatom** [comment]
no worries was a valid question ;)

**Comment by waveatom** [comment]
Checks seem hung up.

**Comment by eahefnawy** [comment]
Thanks for sharing @waveatom 

@patrickr question is valid because the name is misleading imo. I'd call it plugin-boilerplate or something. But we already have that in core with the `serverless create` command:
https://github.com/waveatom/serverless-do-nothing

**Comment by waveatom** [comment]
The intent of this was to create a template project not a template class which is what serverless create does.

**Comment by eahefnawy** [comment]
@waveatom sounds reasonable. I highly recommend changing the name, or at least the description though. It's really unclear why I should use this plugin.

**Comment by medikoo** [comment]
Closing due to lack of response

**Pull request closed without merging**
