### PR TITLE
Add serverless-mongodb-local to plugin list

### PR DESCRIPTION
**Pull request by DavidBeale**

### CODE REVIEW

**Review by pgrzesik — CHANGES_REQUESTED** [review]
Thank you @DavidBeale :bow: Still, let's keep the CI change outside of this PR

**Comment by DavidBeale** [comment]
> Thank you @DavidBeale 🙇 Still, let's keep the CI change outside of this PR

So another PR for that? Build fails with the old node version.

**Comment by pgrzesik** [comment]
Thank you @DavidBeale :bow: Could you please rebase your PR on top of master so the CI build will run again?

**Comment by DavidBeale** [comment]
> Thank you @DavidBeale 🙇 Could you please rebase your PR on top of master so the CI build will run again?

Done

**Review by pgrzesik — APPROVED** [review]
well done, thank you @DavidBeale :bow:

**Pull request merged**
