### PR TITLE
Added Basic Authentication plugin

### PR DESCRIPTION
**Pull request by svdgraaf**
Added entry for my new plugin: HTTP Basic authentication for your api in api gateway, using Api Gateway API tokens:

https://github.com/svdgraaf/serverless-basic-authentication

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks @svdgraaf ... could you update the README as well? 😊 

> After adding your plugin to the plugins.json file, run npm run docs to regenerate the plugin list table in the readme.md file.

**Comment by svdgraaf** [comment]
@eahefnawy crap, sorry, on it!

**Comment by svdgraaf** [comment]
@eahefnawy done!

**Comment by eahefnawy** [comment]
haha thanks!

**Pull request merged**
