### PR TITLE
Add: serverless-plugin-resource-tagging

### PR DESCRIPTION
**Pull request by ilayanambi86**
Plugin to support stackTags based AWS resource tagging and APIGateway tagging.

[Plugin Link](https://github.com/ilayanambi86/serverless-plugin-resource-tagging)

### CODE REVIEW

**Comment by ilayanambi86** [comment]
Sure @eahefnawy .

**Comment by eahefnawy** [comment]
@ilayanambi86 thanks, I just merged another PR. Could you resolve the conflicts?

Sorry about that 😊

**Comment by ilayanambi86** [comment]
Np @eahefnawy. Sure.

**Comment by ilayanambi86** [comment]
@eahefnawy Resolved conflicts and regenerated README.

**Pull request merged**
