### PR TITLE
feat(plugin): Add serverless-plugin-warmup to list

### PR DESCRIPTION
**Pull request by goncaloneves**
Thanks in advance!

### CODE REVIEW

**Comment by DavidWells** [comment]
@goncaloneves this is super cool! Thanks for the plugin

**Comment by goncaloneves** [comment]
@DavidWells thanks David! 😄  The days of cold SLS lambdas are over.

**Comment by pmuens** [comment]
Super cool plugin! Thanks for creating and sharing @goncaloneves 👍 ♨️

**Comment by DavidWells** [comment]
@goncaloneves would you be interested in sharing this on our blog? Would love to feature something like this =)

**Comment by goncaloneves** [comment]
Absolutely David! Pleasure, let me know if you need any help. Cheers! ;)

**Pull request merged**
