### PR TITLE
adding serverless-apigw-sqs-plugin

### PR DESCRIPTION
**Pull request by CodeRecipe-dev**

### CODE REVIEW

**Comment by eahefnawy** [comment]
Thanks @CodeRecipe-dev  ... as soon as you resolve the conflicts I'll merge right away! :shipit:

**Comment by CodeRecipe-dev** [comment]
fixed the conflict

**Comment by CodeRecipe-dev** [comment]
ping @eahefnawy

**Comment by eahefnawy** [comment]
Thanks @CodeRecipe-dev ... sorry for the slow reply.

**Pull request merged**
